stages:
    - lint


lint_shell:
    stage: lint
    image: koalaman/shellcheck-alpine:latest
    script: 
    - shellcheck **/*.sh

lint_yaml:
    stage: lint
    image: python:3.9
    script:
        - pip install yamllint
        - yamllint r .