global:
  scrape_interval: 15s  # Default scrape interval for all targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scraping Prometheus itself
  - job_name: 'proxmox'
    static_configs:
      - targets: ['pve:9100']  # Replace with the IP address of a target server (Node Exporter)
  - job_name: 'admin'
    static_configs:
      - targets: ['admin:9100'] 
  - job_name: 'gitlab'
    static_configs:
      - targets: ['gitlab:9100']
  - job_name: 'runner'
    static_configs:
      - targets: ['runner:9100']
